import {
  attribute,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';
import IBook from './book.interface';
import { ApiModelProperty } from '@nestjs/swagger';

@table('books')
export default class Book implements IBook {
  @autoGeneratedHashKey()
  @ApiModelProperty({
    type: 'string',
    description: 'uuid',
    example: 'a3bbeb1f-b3cb-495a-b055-578fd221a00a',
  })
  id: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The title of book',
    example: 'Web API: The Good Parts',
  })
  title: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The auther of book',
    example: '水野 貴明',
  })
  author?: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The image url of book',
    example:
      'https://images-na.ssl-images-amazon.com/images/I/51GHwTNJgSL._SX389_BO1,204,203,200_.jpg',
  })
  imgUrl?: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The International Standard Book Number (isbn) of book',
    example: '4873116864',
  })
  isbn10?: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The International Standard Book Number (isbn) of book',
    example: '978-4873116860',
  })
  isbn13?: string;

  @attribute({ defaultProvider: () => new Date() })
  @ApiModelProperty({
    type: 'string',
    description: 'created date time',
    format: 'date-time',
    example: '2019-10-13T06:08:16.000Z',
  })
  createdAt: Date;
}
