import {
  attribute,
  rangeKey,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';
import IBook from './book.interface';

@table('books')
export default class Book implements IBook {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  title: string;

  @rangeKey({ defaultProvider: () => new Date() })
  createdAt: Date;
}
