import {
  attribute,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';
import IBook from './book.interface';
import { ApiModelProperty } from '@nestjs/swagger';

@table('books')
export default class Book implements IBook {
  @autoGeneratedHashKey()
  @ApiModelProperty({
    type: 'string',
    description: 'uuid',
    example: 'a3bbeb1f-b3cb-495a-b055-578fd221a00a',
  })
  id: string;

  @attribute()
  @ApiModelProperty({
    type: 'string',
    description: 'The title of book',
    example: 'Web API: The Good Parts',
  })
  title: string;

  @attribute({ defaultProvider: () => new Date() })
  @ApiModelProperty({
    type: 'string',
    description: 'created date time',
    format: 'date-time',
    example: '2019-10-13T06:08:16.000Z',
  })
  createdAt: Date;
}
